// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8sE_w7_nClz7l0jqB2tLl5iuo3eeLV5U',
    appId: '1:775703597505:web:63491f9faf510e6f169f40',
    messagingSenderId: '775703597505',
    projectId: 'flutterauth-9ba4b',
    authDomain: 'flutterauth-9ba4b.firebaseapp.com',
    storageBucket: 'flutterauth-9ba4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwcoJvEroxAypoHbRbvbaskhLso1yHa5Y',
    appId: '1:775703597505:android:c9f036de9c832f90169f40',
    messagingSenderId: '775703597505',
    projectId: 'flutterauth-9ba4b',
    storageBucket: 'flutterauth-9ba4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmCJ5V420JSi_30pHyVlGx9a2JJGF0AYo',
    appId: '1:775703597505:ios:b2e857759a5ebda4169f40',
    messagingSenderId: '775703597505',
    projectId: 'flutterauth-9ba4b',
    storageBucket: 'flutterauth-9ba4b.firebasestorage.app',
    iosBundleId: 'com.example.welcomeScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmCJ5V420JSi_30pHyVlGx9a2JJGF0AYo',
    appId: '1:775703597505:ios:b2e857759a5ebda4169f40',
    messagingSenderId: '775703597505',
    projectId: 'flutterauth-9ba4b',
    storageBucket: 'flutterauth-9ba4b.firebasestorage.app',
    iosBundleId: 'com.example.welcomeScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8sE_w7_nClz7l0jqB2tLl5iuo3eeLV5U',
    appId: '1:775703597505:web:05d27504cb7722a3169f40',
    messagingSenderId: '775703597505',
    projectId: 'flutterauth-9ba4b',
    authDomain: 'flutterauth-9ba4b.firebaseapp.com',
    storageBucket: 'flutterauth-9ba4b.firebasestorage.app',
  );
}
